//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiplomosEntities2 : DbContext
    {
        public DiplomosEntities2()
            : base("name=DiplomosEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FullLecture> FullLecture { get; set; }
        public virtual DbSet<ImageUsers> ImageUsers { get; set; }
        public virtual DbSet<Rezult> Rezult { get; set; }
        public virtual DbSet<Test1> Test1 { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
