//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test1
    {
        public int Id { get; set; }
        public int Nomer_testa { get; set; }
        public int Nomer_voprosa { get; set; }
        public string Vopros { get; set; }
        public string Var_otveta_1 { get; set; }
        public string Var_otveta_2 { get; set; }
        public string Var_otveta_3 { get; set; }
        public string Var_otveta_4 { get; set; }
        public string Prav_otvet { get; set; }
    }
}
